### ISSUE TITLE
Crashing when exporting 'recruit' to latest blender

### ISSUE THREAD

**Issue by sspookifyy** [h4lfheart/FortnitePorting#70]
I have reset settings, made sure 4.2 blender was selected, installed c++ redist and .net and every time im freeze on the bar being halfway when i click export and then my log sometimes shows errors then crashes. ive built the exe also with commands and still no luck. i have 32gb of ram for anyone wondering
![image](https://github.com/user-attachments/assets/b13a7c99-ce90-4f9e-9aae-6256e66fac40)
![image](https://github.com/user-attachments/assets/50baf022-f613-41aa-83dd-529aed198932)

**Comment by Tevtongermany** [comment]
Make sure your uefn is updated since recently it has been doing that because of UEFN not being updated for some reason
if you did update uefn and have everything recent don't worry, it's just an ongoing bug will be fixed later 
and if you didn't already join the discord, we can help you there easier!

**Comment by h4lfheart** [comment]
fixed in latest
